"""The value source: bytes an operator holds, checked against the plan before
anything is dialled.

The layout is `<dir>/<entry-key>/<file>`, and an entry key carries a `/` of its
own (`issuer:vars/session`), so `<dir>/issuer:vars/session/token` is a real
nested path. A file claims to be a value's where it lies under that value's own
directory, so the source is enumerated under the directory of every value entry
the deployment delivers and a file under none of them is measured by nothing. A
declared file is addressed by joining the key and the name rather than by
splitting a relative path back into the two.

The required set is exactly the declared files of every value entry whose
delivery set is non-empty and which records no `program`. Bytes are needed only
for a file that will actually be written, and the plan carries the bytes of
nothing, so what a value entry states about being in the plan is not consulted
here. A value recording a `program` is generated by the external secret
generator and delivered by that tool's own deploy step, so the operator holds
none of its bytes: it is asked for none, and a source holding one is refused
rather than written.

When `--only` restricts the run the missing-file check is restricted with it: to
the value entries whose delivery set intersects the machines of the selected
entries, plus any value entry `--only` names directly. What the source holds is
still measured against every value the whole deployment delivers, so a source
that is right for the deployment stays right for a restricted run of it, and a
deployment that delivers no value takes an empty source and nothing else.
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path

from errors import ApplyError
from manifest import Deployment, Value, ValueFile


def delivered(deployment: Deployment) -> tuple[str, ...]:
    """Return the keys of the value entries some machine receives, sorted."""
    return tuple(key for key, value in sorted(deployment.values.items()) if value.delivery)


def reaching(
    deployment: Deployment, machines: Iterable[str], named: Iterable[str]
) -> dict[str, tuple[str, ...]]:
    """Return the value entries a run must hold bytes for, and where each goes.

    Args:
        deployment: The deployment being applied.
        machines: The machines of the entries the run applies.
        named: The keys `--only` named, which may include a value entry.

    Returns:
        Each delivered value key the run is answerable for, in key order, with
        the machines of its delivery set this run writes it to. A value the run
        reaches because a selected entry's machine receives it is written to
        the machines it selected and to no others, so a machine that receives
        the value only because an unselected entry reads it is not dialled. A
        value named directly is written to its whole delivery set.
    """
    reached = frozenset(machines)
    wanted = frozenset(named)
    answerable: dict[str, tuple[str, ...]] = {}
    for key in delivered(deployment):
        delivery = deployment.values[key].delivery
        if key in wanted:
            answerable[key] = delivery
        elif reached.intersection(delivery):
            answerable[key] = tuple(machine for machine in delivery if machine in reached)
    return answerable


def required(deployment: Deployment, keys: Iterable[str]) -> tuple[tuple[Value, ValueFile], ...]:
    """Return every file that will be written, by value entry then file name.

    Args:
        deployment: The deployment being applied.
        keys: The value entries under consideration.

    Returns:
        Each delivered value entry that records no `program`, paired with each
        file it declares.
    """
    return tuple(
        (value, file)
        for key in sorted(set(keys))
        for value in (deployment.values[key],)
        if value.delivery and value.program is None
        for file in value.files
    )


def generated(deployment: Deployment) -> tuple[tuple[Value, ValueFile], ...]:
    """Return every file of a delivered value the external generator delivers.

    Args:
        deployment: The deployment being applied.

    Returns:
        Each delivered value entry recording a `program`, paired with each file
        it declares.
    """
    return tuple(
        (value, file)
        for key in delivered(deployment)
        for value in (deployment.values[key],)
        if value.program is not None
        for file in value.files
    )


def held(root: Path, keys: Iterable[str]) -> tuple[str, ...]:
    """Return the files the source holds for ``keys``, relative to it, sorted.

    Args:
        root: The value source.
        keys: The value entries the deployment delivers.

    Returns:
        Every file under one of those entries' own directories. A file under
        none of them makes no claim about a value, so it is not measured.
    """
    return tuple(
        sorted(
            found.relative_to(root).as_posix()
            for key in keys
            for found in (root / key).rglob("*")
            if found.is_file()
        )
    )


def check(deployment: Deployment, root: Path | None, keys: Iterable[str]) -> None:
    """Refuse a value source that does not match the plan, before anything is dialled.

    Args:
        deployment: The deployment being applied.
        root: The value source, or ``None`` when the operator named none.
        keys: The value entries this run is answerable for.

    Raises:
        ApplyError: If the source is not a directory, if it holds no bytes for a
            file a delivered value the operator supplies declares, if it holds a
            file of a value the external generator delivers, or if it holds a
            file no delivered value of the deployment declares.
    """
    if root is not None and not root.is_dir():
        raise ApplyError(f"the value source {root} is not a directory")
    present = frozenset(held(root, delivered(deployment))) if root is not None else frozenset()

    for value, file in required(deployment, keys):
        relative = f"{value.key}/{file.name}"
        if relative in present:
            continue
        if root is None:
            raise ApplyError(
                f"{value.key} declares {file.name}, delivered to "
                f"{', '.join(value.delivery)}, and no value source was named"
            )
        raise ApplyError(
            f"{value.key} declares {file.name} and the value source holds no {relative}"
        )

    mine = {f"{value.key}/{file.name}": value for value, file in generated(deployment)}
    theirs = sorted(present.intersection(mine))
    if theirs:
        owner = mine[theirs[0]]
        raise ApplyError(
            f"the value source holds {theirs[0]}, and the bytes of {owner.key} are the "
            f"generator's: {owner.program} produces them and the generator's own deploy "
            f"step delivers them"
        )

    everything = frozenset(
        f"{value.key}/{file.name}" for value, file in required(deployment, delivered(deployment))
    )
    extra = sorted(present - everything)
    if extra:
        raise ApplyError(
            f"the value source holds {', '.join(extra)}, which no value this deployment "
            f"delivers declares"
        )


def bytes_of(root: Path, value: Value, file: ValueFile) -> bytes:
    """Return the bytes the source holds for one declared file.

    Args:
        root: The value source.
        value: The value entry the file belongs to.
        file: The declared file.

    Returns:
        The file's bytes, as they will be written.

    Raises:
        ApplyError: If the file cannot be read.
    """
    path = root / value.key / file.name
    try:
        return path.read_bytes()
    except OSError as unreadable:
        raise ApplyError(f"{value.key}: {path} cannot be read: {unreadable}") from unreadable
