# One plan, the generator configuration read out of it, and the three flakelet
# artifacts a machine takes. Nothing here carries a generated byte: the values of
# this folder are minted by a real generator during the run, stored by a real
# backend, and delivered by the step `secrets/backend.nix` rendered from the plan.
#
# The plan is built twice on purpose. This one is evaluated against the declared
# state - every file present, no bytes - so the unit files and the configuration
# are a function of the declaration alone. The run re-evaluates the same
# deployment through `plan.nix` against what the backend answered, and that is the
# plan every assertion reads.
#
# The reading and the deploy step arrive as arguments rather than by relative
# path: a folder of this layer reads no file outside itself, which is what keeps
# it readable on its own.
{
  pkgs,
  planner,
  flakeletBuilder,
  reader,
  deployStep,
  korora,
  nixpkgs,
  libSource,
}:
let
  python3 = "${pkgs.python3Minimal}";

  # A single executable file rather than a `bin` directory: the generator realises
  # a derivation and runs its output as a program, so the output has to be one.
  program =
    name: source:
    pkgs.writeTextFile {
      name = "planner-e2e-${name}";
      executable = true;
      text = ''
        #!${python3}/bin/python3
        ${builtins.readFile source}
      '';
    };

  mint = program "mint" ./mint.py;
  derive = program "derive" ./derive.py;

  backendSource = pkgs.writeText "planner-e2e-age-backend.py" (builtins.readFile ./backend.py);

  # One program per command of the contract's store backend, each with `age` and
  # coreutils on its path. The storage root, the recipient and the identity are
  # the run's, so they arrive from the environment.
  backendCommand =
    command:
    pkgs.writeTextFile {
      name = "planner-e2e-age-${command}";
      executable = true;
      text = ''
        #!${pkgs.runtimeShell}
        PATH=${pkgs.age}/bin:${pkgs.coreutils}/bin:$PATH
        export PATH
        exec ${python3}/bin/python3 ${backendSource} ${command} "$@"
      '';
    };

  ageCommands = builtins.listToAttrs (
    map
      (command: {
        name = command;
        value = backendCommand command;
      })
      [
        "get"
        "set"
        "exists"
        "delete"
        "list"
        "fixup"
      ]
  );

  # The library has no prompt vocabulary, so nothing it plans can ask a question.
  # A prompt asked at all is a defect, and this makes it a named failure rather
  # than a wedged run.
  refuse = pkgs.writeTextFile {
    name = "planner-e2e-prompt-refused";
    executable = true;
    text = ''
      #!${pkgs.runtimeShell}
      echo "planner-e2e: $1/$2 asked a prompt, and a plan carries none" >&2
      exit 1
    '';
  };

  packages = {
    inherit python3;
    coreutils = "${pkgs.coreutils}";
    issueScript = "${pkgs.writeText "generated-secret-issue.py" (builtins.readFile ./issue.py)}";
    attestScript = "${pkgs.writeText "generated-secret-attest.py" (builtins.readFile ./attest.py)}";
    mintProgram = mint.drvPath;
    deriveProgram = derive.drvPath;
  };

  deployment = import ./deployment { inherit planner packages; };
  result = planner.mkPlan deployment.args;

  keys = {
    issuer = "issuer:api@alpha";
    probe = "probe:client@beta";
    idle = "idle:job@gamma";
  };

  varsKeys = {
    root = "issuer:vars/root";
    token = "issuer:vars/token";
  };

  entries = builtins.mapAttrs (
    _: key:
    flakeletBuilder.artifact {
      plan = result.plan;
      inherit key;
    }
  ) keys;

  # The step the contract hands a file list and no target. `get` is the backend's
  # own, because the step names paths and machines and reads the bytes at run time.
  deployRemote = pkgs.writeTextFile {
    name = "planner-e2e-deploy-remote";
    executable = true;
    text = ''
      #!${pkgs.runtimeShell}
      PATH=${pkgs.openssh}/bin:${pkgs.coreutils}/bin:$PATH
      export PATH
      exec ${pkgs.runtimeShell} ${
        pkgs.writeText "planner-e2e-deploy-remote.sh" (
          deployStep.render {
            plan = result.plan;
            get = "${ageCommands.get}";
          }
        )
      } "$@"
    '';
  };

  configuration = reader.configuration {
    plan = result.plan;
    backend = "age";
    backends = {
      prompt.refused.ask = refuse.drvPath;
      store.age = {
        get = ageCommands.get.drvPath;
        set = ageCommands.set.drvPath;
        exists = ageCommands.exists.drvPath;
        delete = ageCommands.delete.drvPath;
        list = ageCommands.list.drvPath;
        fixup = ageCommands.fixup.drvPath;
        deploy = {
          local = null;
          remote = deployRemote.drvPath;
        };
      };
    };
  };

  names = builtins.listToAttrs (
    map (value: {
      name = value.key;
      value = value.name;
    }) (reader.valuesOf result.plan)
  );

  # The plan of this deployment against a state read at run time. A plan carrying
  # generated bytes cannot be a build artifact of a run that has generated nothing
  # yet, so the run evaluates this file instead of reading `plan.json`.
  planExpression = pkgs.writeText "planner-generated-secret-plan.nix" ''
    { varsStateFile }:
    let
      planner = import ${libSource} {
        korora = import ${korora}/types.nix;
        systems = (import ${nixpkgs}/lib).systems;
      };
      deployment = import ${./deployment} {
        inherit planner;
        packages = builtins.fromJSON ${builtins.toJSON (builtins.toJSON packages)};
        varsState = builtins.fromJSON (builtins.readFile varsStateFile);
      };
    in
    planner.mkPlan deployment.args
  '';

  files = [
    {
      # The same `age` the store backend runs, so a run mints its identity with
      # it rather than with whatever the host happens to carry.
      name = "age";
      path = pkgs.age;
    }
    {
      name = "plan.json";
      path = pkgs.writeText "planner-generated-secret.json" (builtins.toJSON result.plan);
    }
    {
      name = "secrets.json";
      path = pkgs.writeText "planner-generated-secret-config.json" (builtins.toJSON configuration);
    }
    {
      name = "names.json";
      path = pkgs.writeText "planner-generated-secret-names.json" (builtins.toJSON names);
    }
    {
      name = "plan.nix";
      path = planExpression;
    }
  ];
in
(pkgs.linkFarm "planner-generated-secret-artifacts" (
  files
  ++ map (name: {
    inherit name;
    path = entries.${name};
  }) (builtins.attrNames entries)
)).overrideAttrs
  (old: {
    passthru = (old.passthru or { }) // {
      inherit
        entries
        keys
        varsKeys
        names
        configuration
        ;
      plan = result;
    };
  })
